apiVersion: v1
kind: Service
metadata:
  labels:
    app: openshift4-nightly-reinstall
  name: openshift4-nightly-reinstall
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: openshift4-nightly-reinstall
    deploymentconfig: openshift4-nightly-reinstall
